[project]
name = "nanays_kakanin"
provider = "django"
app_dir = "."
manage_path = "manage.py"
python_version = "3.11"

[build]
commands = [
  "pip install -r requirements.txt",
  "python manage.py collectstatic --noinput"
]

[run]
command = "python manage.py runserver 0.0.0.0:${PORT}"