[project]
name = "nanays-kakanin"
version = "1.0.0"

[build]
command = "pip install -r requirements.txt"

[deploy]

command = "python manage.py migrate && gunicorn nanays_kakanin.wsgi:application --bind 0.0.0.0:${PORT}"
